# Generated by Django 4.0.4 on 2022-04-18 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='id пользователя')),
                ('status_bot', models.BooleanField(default=False, verbose_name='Статус бота')),
                ('created_user', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_user'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sub', models.CharField(max_length=50, verbose_name='Название подписки')),
                ('type_sub', models.CharField(choices=[('kolesa', 'kolesa'), ('krisha', 'krisha')], max_length=50, verbose_name='Тип подписки')),
                ('limit_filters', models.IntegerField(blank=True, null=True, verbose_name='Лимит фильтров')),
                ('days_sub', models.IntegerField(verbose_name='Количество дней подписки')),
                ('price_sub', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Цена подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['type_sub'],
            },
        ),
        migrations.CreateModel(
            name='SubscribeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_sub', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('sub_log_type_sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posting.subscribe', verbose_name='Тип подписки')),
                ('sub_log_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posting.client', to_field='user_id', verbose_name='id пользователя')),
            ],
            options={
                'verbose_name': 'Лог подписки',
                'verbose_name_plural': 'Логи подписок',
                'ordering': ['-created_sub'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_mess', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
                ('log_text', models.TextField(verbose_name='Текст сообщения')),
                ('mess_log_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posting.client', to_field='user_id', verbose_name='id пользователя')),
            ],
            options={
                'verbose_name': 'Лог сообщения',
                'verbose_name_plural': 'Логи сообщений',
                'ordering': ['-created_mess'],
            },
        ),
    ]
