# Generated by Django 4.0.4 on 2022-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='list_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
